# All alternate name should be in lowercase
BOSSES = [
	{
		"id": 1,
		"name": "Zakum, Hilla, Pink Bean, Cygnus",
		"alt_name": ["czak", "hhilla", "cpb", "ncyg", "chaos zakum", "hard hilla", "chaos pink bean", "normal cygnus"],
		"difficulty": "Hard",
		"solo_floor": 36,
		"party_floor_4_man": None,
		"party_floor_6_man_new": None,
		"party_floor_6_man_experienced": None,
		"priority": 100,
	},
	{
		"id": 2,
		"name": "Magnus",
		"alt_name": ["hmag", "hard magnus"],
		"difficulty": "Hard",
		"solo_floor": 40,
		"party_floor_4_man": None,
		"party_floor_6_man_new": None,
		"party_floor_6_man_experienced": None,
		"priority": 300,
	},
	{
		"id": 3,
		"name": "Root Abyss",
		"alt_name": ["cra", "queen", "clown", "kfc", "chicken", "vellum", "chaos root abyss"],
		"difficulty": "Chaos",
		"solo_floor": 36,
		"party_floor_4_man": None,
		"party_floor_6_man_new": None,
		"party_floor_6_man_experienced": None,
		"priority": 200,
	},
	{
		"id": 4,
		"name": "Papulatus",
		"alt_name": ["cpap", "papu", "chaos papulatus", "cpapu", "chaos papu"],
		"difficulty": "Chaos",
		"solo_floor": 44,
		"party_floor_4_man": None,
		"party_floor_6_man_new": None,
		"party_floor_6_man_experienced": None,
		"priority": 400, 
	}, 
	{
		"id": 5,
		"name": "Princess Nou",
		"alt_name": ["pnou"],
		"difficulty": "Chaos",
		"solo_floor": None,
		"party_floor_4_man": None,
		"party_floor_6_man_new": None,
		"party_floor_6_man_experienced": None,
		"priority": 500,
	},
	{
		"id": 6,
		"name": "Akechi",
		"alt_name": ["ake"],
		"difficulty": "Normal",
		"solo_floor": 44,
		"party_floor_4_man": None,
		"party_floor_6_man_new": None,
		"party_floor_6_man_experienced": None,
		"priority": 600,
	},
	{
		"id": 7,
		"name": "Lotus",
		"alt_name": ["nlo", "nlomien", "lomien", "normal lotus"],
		"difficulty": "Normal",
		"solo_floor": 44,
		"party_floor_4_man": 40,
		"party_floor_6_man_new": None,
		"party_floor_6_man_experienced": 36,
		"priority": 700,
	},
	{
		"id": 8,
		"name": "Damien",
		"alt_name": ["ndam", "nlomien", "lomien", "normal damien"],
		"difficulty": "Normal",
		"solo_floor": 44,
		"party_floor_4_man": 40,
		"party_floor_6_man_new": None,
		"party_floor_6_man_experienced": 37,
		"priority": 800,
	},
	{
		"id": 9,
		"name": "Divine King Slime",
		"alt_name": ["nslime", "slime", "guardian angel slime", "ga slime", "normal slime"],
		"difficulty": "Normal",
		"solo_floor": 47,
		"party_floor_4_man": 44,
		"party_floor_6_man_new": None,
		"party_floor_6_man_experienced": None,
		"priority": 900,
	},
	{
		"id": 10,
		"name": "Lucid",
		"alt_name": ["elu", "easy lucid", "elucid"],
		"difficulty": "Easy",
		"solo_floor": 49,
		"party_floor_4_man": 44,
		"party_floor_6_man_new": None,
		"party_floor_6_man_experienced": 42,
		"priority": 1000,
	},
	{
		"id": 11,
		"name": "Lucid",
		"alt_name": ["nlu", "normal lucid", "nlucid"],
		"difficulty": "Normal",
		"solo_floor": 50,
		"party_floor_4_man": 47,
		"party_floor_6_man_new": 46,
		"party_floor_6_man_experienced": 44,
		"priority": 1200
	},
	{
		"id": 12,
		"name": "Will",
		"alt_name": ["nwill", "normal will"],
		"difficulty": "Normal",
		"solo_floor": 50,
		"party_floor_4_man": None,
		"party_floor_6_man_new": 47,
		"party_floor_6_man_experienced": 44,
		"priority": 1300
	},
	{
		"id": 13,
		"name": "Dusk",
		"alt_name": ["ndusk", "normal dusk"],
		"difficulty": "Normal",
		"solo_floor": 50,
		"party_floor_4_man": 50,
		"party_floor_6_man_new": 50,
		"party_floor_6_man_experienced": None,
		"priority": 1400
	},
	{
		"id": 14,
		"name": "Djunkel",
		"alt_name": ["ndjunkel", "njunkel", "junkel", "normal djunkel"],
		"difficulty": "Normal",
		"solo_floor": 50,
		"party_floor_4_man": 50,
		"party_floor_6_man_new": 50,
		"party_floor_6_man_experienced": None,
		"priority": 1500
	},
	{
		"id": 15,
		"name": "Damien",
		"alt_name": ["hdam", "hlomien", "lomien", "hard damien"],
		"difficulty": "Hard",
		"solo_floor": 54,
		"party_floor_4_man": 50,
		"party_floor_6_man_new": 50,
		"party_floor_6_man_experienced": 47,
		"priority": 1700
	},
	{
		"id": 16,
		"name": "Lotus",
		"alt_name": ["hlo", "hlomien", "lomien", "hard lotus"],
		"difficulty": "Hard",
		"solo_floor": 54,
		"party_floor_4_man": 50,
		"party_floor_6_man_new": 50,
		"party_floor_6_man_experienced": 47,
		"priority": 1600
	},
	{
		"id": 17,
		"name": "Lucid",
		"alt_name": ["hlu", "hard lucid", "hlucid"],
		"difficulty": "Hard",
		"solo_floor": 57,
		"party_floor_4_man": 54,
		"party_floor_6_man_new": 50,
		"party_floor_6_man_experienced": None,
		"priority": 1800
	},
	{
		"id": 18,
		"name": "Will",
		"alt_name": ["hwill", "hard will"],
		"difficulty": "Hard",
		"solo_floor": 57,
		"party_floor_4_man": 54,
		"party_floor_6_man_new": 50,
		"party_floor_6_man_experienced": None,
		"priority": 1900
	},
	{
		"id": 19,
		"name": "Dusk",
		"alt_name": ["cdusk", "chaos dusk"],
		"difficulty": "Chaos",
		"solo_floor": 58,
		"party_floor_4_man": 58,
		"party_floor_6_man_new": 57,
		"party_floor_6_man_experienced": 54,
		"priority": 2000
	},
	{
		"id": 20,
		"name": "Djunkel",
		"alt_name": ["hdjunkel", "hjunkel", "junkel", "hard djunkel"],
		"difficulty": "Hard",
		"solo_floor": 58,
		"party_floor_4_man": 58,
		"party_floor_6_man_new": 57,
		"party_floor_6_man_experienced": 54,
		"priority": 2100
	},
	{
		"id": 21,
		"name": "Heretic Hilla",
		"alt_name": ["vhilla", "hard heretic hilla", "versus hilla"],
		"difficulty": "Hard",
		"solo_floor": 58,
		"party_floor_4_man": 58,
		"party_floor_6_man_new": 57,
		"party_floor_6_man_experienced": 54,
		"priority": 2200
	},
	{
		"id": 22,
		"name": "Divine King Slime",
		"alt_name": ["cslime", "slime", "guardian angel slime", "ga slime","chaos slime"],
		"difficulty": "Hard",
		"solo_floor": 58,
		"party_floor_4_man": 58,
		"party_floor_6_man_new": 57,
		"party_floor_6_man_experienced": None,
		"priority": 2300
	},
	{
		"id": 23,
		"name": "Black Mage",
		"alt_name": ["bm", "hard black mage"],
		"difficulty": "Hard",
		"solo_floor": None,
		"party_floor_4_man": None,
		"party_floor_6_man_new": 57,
		"party_floor_6_man_experienced": 55,
		"priority": 2400
	},
	{
		"id": 24,
		"name": "Will",
		"alt_name": ["ewill", "easy will"],
		"difficulty": "Easy",
		"solo_floor": None,
		"party_floor_4_man": None,
		"party_floor_6_man_new": None,
		"party_floor_6_man_experienced": None,
		"priority": 1100
	},
]

BOSSES = sorted(BOSSES, key=lambda boss: boss['priority'])